name: donate2save
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

# Firebase dependencies
  firebase_core: ^3.10.1      # Required to initialize Firebase
  firebase_auth: ^5.4.1       # Sign in / Sign up / Email verification, etc.
  cloud_firestore: ^5.6.2     # Cloud-based NoSQL database for storing user data
  
# UI
  flutter_spinkit: ^5.2.0     # Prebuilt animated loading indicators
  lottie: ^3.2.0              # Render Lottie JSON animations in your app
  cupertino_icons: ^1.0.8     # Apple's official icon pack for iOS-like UI

# State Management & Utilities
  provider: ^6.1.2            # Easy and scalable state management solution
  dartz: ^0.10.1              # Functional programming library for Dart, useful for handling Optionals and Either types 

# Localization
  flutter_localizations:       # Enables multilingual UI (built into Flutter SDK)
    sdk: flutter            
  intl: ^0.20.2               # Internationalization and localization support

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0       # Linting rules for Flutter projects
  flutter_native_splash: ^2.4.4 # Auto-generates splash screens for Android/iOS
  flutter_launcher_icons: ^0.14.4 # Creates app launcher icons for Android/iOS
  intl_utils: ^2.8.0    # Generates `.dart` localization files from `.arb`

flutter_launcher_icons:
  android: "launcher_icon"
  android_adaptive_icon: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_icon.png"

flutter_native_splash:
  android: true
  fullscreen: true
  background_image: assets/splash_screen_white.png
  background_image_dark: assets/splash_screen_dark.png

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/app_icon.png
    - assets/heart_logo.png
    - assets/animations/loading_heart.json
    - assets/splash_screen_white.png
    - assets/splash_screen_dark.png